name:                validate
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/state#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:

dependencies:
  - base >= 4.7 && < 5
  - mtl

executables:
  state:
    source-dirs:      src
    main:             Main.hs
